<small><small><i>
All the IPython Notebooks in this **Python Examples** series by Dr. Milaan Parmar are available @ **[GitHub](https://github.com/milaan9/90_Python_Examples)**
</i></small></small>

# Python Matrices and NumPy Arrays

In this class, we will learn about Python matrices using nested lists, and NumPy package.

A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. For example:

## NumPy Array Types:

<div>
<img src="img/matrix1.png" width="300"/>
</div>

## Python Matrix

Python doesn't have a built-in type for matrices. However, we can treat a list of a list as a matrix. For example:

In [1]:
A = [[1, 3, 6], 
    [-7, 8, 9]]
A

[[1, 3, 6], [-7, 8, 9]]



Be sure to learn about **[Python lists](https://github.com/milaan9/02_Python_Datatypes/blob/main/003_Python_List.ipynb)** before proceed this article.

We can treat this list of a list as a matrix having 2 rows and 3 columns.

<div>
<img src="img/matrix2.png" width="130"/>
</div>

In [2]:
# Let's see how to work with a nested list.

A = [[1, 3, 6, 12], 
    [-7, 8, 9, 0],
    [-5, 7, 12, 19]]

print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

column = [];        # empty list
for row in A:
    column.append(row[2])   

print("3rd column =", column)

A = [[1, 3, 6, 12], [-7, 8, 9, 0], [-5, 7, 12, 19]]
A[1] = [-7, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12
3rd column = [6, 9, 12]


Here are few more examples related to Python matrices using nested lists.

* **[Add two matrices]()**
* **[Transpose a Matrix]()**
* **[Multiply two matrices]()**

Using nested lists as a matrix works for simple computational tasks, however, there is a better way of working with matrices in Python using **[NumPy](https://numpy.org/doc/stable/user/whatisnumpy.html)** package.

# NumPy Array

NumPy is a package for scientific computing which has support for a powerful N-dimensional array object. Before you can use NumPy, you need to install it. For more info,

* Visit: **[How to install NumPy?](https://scipy.org/install.html)**
* If you are on Windows, download and install **[anaconda distribution](https://docs.anaconda.com/anaconda/install/windows/)** of Python. It comes with NumPy and other several packages related to data science and machine learning.

Once NumPy is installed, you can import and use it.

For better understanding visit my **[Numpy Module](https://github.com/milaan9/09_Python_NumPy_Module)** tutorial.

NumPy provides multidimensional array of numbers (which is actually an object). For example:

In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)               # Output: [1, 2, 3]
print(type(a))         # Output: <class 'numpy.ndarray'>

[1 2 3]
<class 'numpy.ndarray'>


As you can see, NumPy's array class is called **`ndarray`**.

## How to create a NumPy array?

For better understanding visit my **[Create a NumPy Array](https://github.com/milaan9/09_Python_NumPy_Module/blob/main/002_Python_NumPy_Array_Part1.ipynb)** tutorial.

There are several ways to create NumPy arrays.

### 1. Array of integers, floats and complex Numbers

In [4]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1 2 3]
 [3 4 5]]
[[1.1 2.  3. ]
 [3.  4.  5. ]]
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


### 2. Array of zeros and ones

In [5]:
import numpy as np

zeors_array = np.zeros( (2, 3) )
print(zeors_array)

'''
 Output:
 [[0. 0. 0.]
  [0. 0. 0.]]
'''

[[0. 0. 0.]
 [0. 0. 0.]]


'\n Output:\n [[0. 0. 0.]\n  [0. 0. 0.]]\n'

In [6]:
ones_array = np.ones( (1, 5), dtype=np.int32 ) # specifying dtype
print(ones_array)      

'''
 Output:
[[1 1 1 1 1]]
'''

[[1 1 1 1 1]]


'\n Output:\n[[1 1 1 1 1]]\n'

**Explanation:**

Here, we have specified **`dtype`** to 32 bits (4 bytes). Hence, this array can take values from $-2^{-31}$ to $2^{-31}-1$.

### 3. Using `arange()` and `shape()`

For better understanding visit my **[NumPy Array reorganizing](https://github.com/milaan9/09_Python_NumPy_Module/blob/main/005_Python_NumPy_Array_Part4.ipynb)** tutorial.

In [7]:
import numpy as np

A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)

''' 
Output:
A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
'''

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


' \nOutput:\nA = [0 1 2 3]\nB = [[ 0  1  2  3  4  5]\n [ 6  7  8  9 10 11]]\n'

Learn more about other ways of **[creating a NumPy array](https://numpy.org/doc/stable/user/basics.creation.html)**.

## Access matrix elements, rows and columns

For better understanding visit my **[NumPy Array indexing](https://github.com/milaan9/09_Python_NumPy_Module/blob/main/003_Python_NumPy_Array_Part2.ipynb)** tutorial.

**1. Access matrix elements**

Similar like lists, we can access matrix elements using index. Let's start with a one-dimensional NumPy array.

In [8]:
import numpy as np
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element     

A[0] = 2
A[2] = 6
A[-1] = 10


Now, let's see how we can access elements of a two-dimensional array (which is basically a matrix).

In [9]:
import numpy as np

A = np.array([[1, 3, 7, 12],
              [-5, 6, 9, 0],
              [-3, 7, 15, 19]])

#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1])   

A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19


**2. Access rows of a Matrix**

In [10]:
import numpy as np

A = np.array([[1, 3, 7, 12],
              [-5, 6, 9, 0],
              [-3, 7, 15, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 1  3  7 12]
A[2] = [-3  7 15 19]
A[-1] = [-3  7 15 19]


**3. Access columns of a Matrix**

In [11]:
import numpy as np

A = np.array([[1, 3, 7, 12],
              [-5, 6, 9, 0],
              [-3, 7, 15, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)

A[:,0] = [ 1 -5 -3]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


## Slicing of a Matrix

Slicing of a one-dimensional NumPy array is similar to a list. If you don't know how slicing for a list works, visit **[Understanding Python's slice notation](https://stackoverflow.com/questions/509211/understanding-slice-notation)**.

In [12]:
import numpy as np
letters = np.array([1, 3, 5, 7, 9, 7, 5])

# 3rd to 5th elements
print(letters[2:5])        # Output: [5, 7, 9]

# 1st to 4th elements
print(letters[:-5])        # Output: [1, 3]   

# 6th to last elements
print(letters[5:])         # Output:[7, 5]

# 1st to last elements
print(letters[:])          # Output:[1, 3, 5, 7, 9, 7, 5]

# reversing a list
print(letters[::-1])       # Output:[5, 7, 9, 7, 5, 3, 1]

[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


Now, let's see how we can slice a matrix.

In [13]:
import numpy as np

A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A[:2, :4])  # two rows, four columns

''' Output:
[[ 1  4  5 12]
 [-5  8  9  0]]
'''


print(A[:1,])  # first row, all columns

''' Output:
[[ 1  4  5 12 14]]
'''

print(A[:,2])  # all rows, second column

''' Output:
[ 5  9 11]
'''

print(A[:, 2:5])  # all rows, third to the fifth column

'''Output:
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]
'''

[[ 1  4  5 12]
 [-5  8  9  0]]
[[ 1  4  5 12 14]]
[ 5  9 11]
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]


'Output:\n[[ 5 12 14]\n [ 9  0 17]\n [11 19 21]]\n'

## Matrix Operations

For better understanding visit my **[NumPy Array Math](https://github.com/milaan9/09_Python_NumPy_Module/blob/main/004_Python_NumPy_Array_Part3.ipynb)** tutorial.

Above, we gave you 3 examples: addition of two matrices, multiplication of two matrices and transpose of a matrix. We used nested lists before to write those programs. Let's see how we can do the same task using NumPy array.

### Addition of Two Matrices

We use **`+`** operator to add corresponding elements of two NumPy matrices.

In [14]:
import numpy as np

A = np.array([[3, 6], [7, -9]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

''' 
Output:
[[12  3]
 [10 -3]]
 '''

[[12  3]
 [10 -3]]


' \nOutput:\n[[12  3]\n [10 -3]]\n '

### Multiplication of Two Matrices

To multiply two matrices, we use **`dot()`** method. Learn more about how **[numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)** works.

>**Note:** **`*`** is used for array multiplication (multiplication of corresponding elements of two arrays) not matrix multiplication.

In [15]:
import numpy as np

A = np.array([[3, 6, 5], [7, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

''' 
Output:
[[30 -6]
 [ 1  4]]
'''

[[30 -6]
 [ 1  4]]


' \nOutput:\n[[30 -6]\n [ 1  4]]\n'

### Transpose of a Matrix

We use **[numpy.transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)** to compute transpose of a matrix.

In [16]:
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

''' 
Output:
[[ 1  2  3]
 [ 1  1 -3]]
'''

[[ 1  2  3]
 [ 1  1 -3]]


' \nOutput:\n[[ 1  2  3]\n [ 1  1 -3]]\n'

As you can see, using NumPy (instead of nested lists) makes it a lot easier to work with matrices, and we haven't even scratched the basics. We suggest you to explore NumPy package in detail especially if you trying to use Python for data science/analytics.

**NumPy Resources you might find helpful:**

* **[NumPy Tutorial](https://numpy.org/doc/stable/user/quickstart.html)**
* **[Numpy reference](https://numpy.org/doc/stable/reference/)**